from component import BasicComponent

class Wheels:
    def __init__(self):
        self.cost_per_shipment = 120
        self.transport_cost_per_palet = 70
        self.transport_cost_per_full_truck = 2100
        self.period_order_to_buyer_wharehouse = 12

        self.alternatives = [
            BasicComponent(
                name='Wheels2drive',
                remanufacturability=.4,
                remanufacturing_cost=50,
                recyclability=.5,
                durability=0.2,
                weight_in_kg=1.5,
                repair_time_discount=.15,
                price_per_piece=140,
                steel=0,
                rubber=.5,
                plastic=0,
                cardboard=0,
                aluminium=1,
                battery_acid=0
            ),
            BasicComponent(
                name='Wheely',
                remanufacturability=.85,
                remanufacturing_cost=27,
                recyclability=.6,
                durability=0,
                weight_in_kg=1.5,
                repair_time_discount=0,
                price_per_piece=150,
                steel=0,
                rubber=.5,
                plastic=0,
                cardboard=0,
                aluminium=1,
                battery_acid=0
            ),
            BasicComponent(
                name='Wheel_light',
                remanufacturability=.5,
                remanufacturing_cost=40,
                recyclability=.65,
                durability=-0.1,
                weight_in_kg=1.3,
                repair_time_discount=0,
                price_per_piece=130,
                steel=0,
                rubber=.5,
                plastic=0,
                cardboard=0,
                aluminium=.8,
                battery_acid=0
            ),
            BasicComponent(
                name='Wheel_standard',
                remanufacturability=.4,
                remanufacturing_cost=30,
                recyclability=.5,
                durability=0,
                weight_in_kg=1.5,
                repair_time_discount=0,
                price_per_piece=100,
                steel=0,
                rubber=.5,
                plastic=0,
                cardboard=0,
                aluminium=1,
                battery_acid=0
            ),
            BasicComponent(
                name='Durawheel',
                remanufacturability=.5,
                remanufacturing_cost=50,
                recyclability=.45,
                durability=0.3,
                weight_in_kg=1.5,
                repair_time_discount=.1,
                price_per_piece=140,
                steel=0,
                rubber=.5,
                plastic=0,
                cardboard=0,
                aluminium=1,
                battery_acid=0
            ),
            BasicComponent(
                name='Steel_wheel',
                remanufacturability=.3,
                remanufacturing_cost=25,
                recyclability=.9,
                durability=0.1,
                weight_in_kg=2,
                repair_time_discount=-.03,
                price_per_piece=80,
                steel=1.5,
                rubber=.5,
                plastic=0,
                cardboard=0,
                aluminium=0,
                battery_acid=0
            ),
            BasicComponent(
                name='C_Wheel',
                remanufacturability=.8,
                remanufacturing_cost=27,
                recyclability=.55,
                durability=0,
                weight_in_kg=1.5,
                repair_time_discount=.05,
                price_per_piece=150,
                steel=0,
                rubber=.5,
                plastic=0,
                cardboard=0,
                aluminium=1,
                battery_acid=0
            )
        ]
